name: device_preview_plus
version: 2.6.1
description: Approximate how your Flutter app looks and performs on another device
homepage: https://github.com/zeshuaro/device_preview_plus

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  device_frame_plus: ^1.5.0
  freezed_annotation: ^3.1.0
  json_annotation: 4.10.0
  shared_preferences: 2.5.4
  collection: ^1.18.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  build_runner: 2.10.5
  freezed: 3.2.4
  json_serializable: 6.12.0
