name: device_preview_plus
version: 2.3.1
description: Approximate how your Flutter app looks and performs on another device
homepage: https://github.com/zeshuaro/device_preview_plus

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  device_frame_plus: ^1.3.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.2
  collection: ^1.18.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.15
  freezed: 3.0.3
  json_serializable: 6.9.4
