name: device_preview_plus
version: 2.2.6
description: Approximate how your Flutter app looks and performs on another device
homepage: https://github.com/zeshuaro/device_preview_plus

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: ">=3.27.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  device_frame: ^1.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.14
  freezed: 2.5.8
  json_serializable: 6.9.3
