name: device_preview_plus
version: 2.4.2
description: Approximate how your Flutter app looks and performs on another device
homepage: https://github.com/zeshuaro/device_preview_plus

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  device_frame_plus: ^1.4.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  collection: ^1.18.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  build_runner: 2.4.15
  freezed: 3.0.6
  json_serializable: 6.9.5
